### ISSUE TITLE
Can not install theme

### ISSUE THREAD

**Issue by JanWelker** [quintagroup/quintagroup.theme.pythonreel#1]
Hi Guys,

I am trying to install your theme via the ZIP file upload. After the upload the following message appears:

"A boilerplate rules.xml was added to your theme, but no index.html file found. Update rules.xml to reference the current theme file."

I am running the latest Plone version 4.3.4.1 (4309)

Thanks for your help,
Jan

**Comment by waldru** [comment]
This is because the way github offer products download. You download the full python product instead of diazo only stuff.

You need to extract "static" folder from downloaded zip, zip and upload it.
